### ISSUE TITLE
[beta] Weather & Time ,  temperature & time format can't change 

### ISSUE THREAD

**Issue by niedi74** [NSPManager/NSPanelManager#137]
the Weather & Time for  ,temperature & Time format can't change to 24 hours & Celsius

**Comment by tpanajott** [comment]
What version are you running? With my testing this was fixed in 0.1.31-public_beta

**Comment by niedi74** [comment]
i can confirm its working with latest version 0.1.31-public_beta

**Comment by niedi74** [comment]
under settings 

Reverse color temperature slider & 
Turn on behavior 
  
can´t change

**Comment by niedi74** [comment]
the panel still shows only fahreit everywhere in state of Celsius

**Comment by tpanajott** [comment]
Did you restart the panel after you saved the changes?

**Comment by niedi74** [comment]
many times..
