### ISSUE TITLE
Repository/Add-on Not Listing In Home Assistant Add-on Store Even Though Repository Is In List

### ISSUE THREAD

**Issue by BrettEBowman** [NSPManager/NSPanelManager#93]
I've added this github repository to the Home Assistant Add-on Store:
![Screenshot 2023-09-23 161445](https://github.com/NSPManager/NSPanelManager/assets/17341309/d8a4e205-2c99-4572-91a7-04bbca27a892)
However, in the Add-on Store screen, neither the Repository or the Add-on are being displayed:
![Screenshot 2023-09-23 161640](https://github.com/NSPManager/NSPanelManager/assets/17341309/fec520b4-cab4-4f16-90b5-4cf0977aad44)

**Comment by tpanajott** [comment]
It seems that the automatic change for version number messed up the configuration file that HA is looking at when listing add-on details. It should be fixed now (manually). Have a look again and check if you can find it.

**Comment by BrettEBowman** [comment]
> It seems that the automatic change for version number messed up the configuration file that HA is looking at when listing add-on details. It should be fixed now (manually). Have a look again and check if you can find it.

Unfortunately, no. I even tried removing the repository and re-adding it. Maybe it is a timing thing. I can try again a little later.

**Comment by tpanajott** [comment]
Had another look and saw that even more things where messed up. Fixed them so hopefully it should work next time you check.

**Comment by BrettEBowman** [comment]
> Had another look and saw that even more things where messed up. Fixed them so hopefully it should work next time you check.

Yes. That got it to show up and install.

Minor thing: on the web gui, the lower right corner is still showing "Version: 0.1.20.1"

**Comment by tpanajott** [comment]
Hm, yhea, will have to take a look at that. There are some issues with the auto-updating of version numbers that need to be looked at.

**Comment by tpanajott** [comment]
This has been resolved, closing.
